### ISSUE TITLE
Can't find FBSDKLoginKit/FBSDKLoginKit.h

### ISSUE THREAD

**Issue by Sherlock92** [facebook/react-native-fbsdk#32]
I'm an IOS newcomer. Took all of the steps described in the MD file, everything looks ok except i'm getting the `FBSDKLoginKit/FBSDKLoginKit.h file not found` build error. What could I have missed here ?

I have tried rebuilding, and adding the Facebook SDK path to frameworks. When i try to import these files in app delegate, there are no errors.

Steps i took:
- `npm install --save react-native-fbsdklogin`
- Add `RCTFBSDKLogin.xcodeproj` to Libraries
- Add `linRCTFBSDKLogin.a` to build phases
- Install Facebook SDK into standard location
- Create a new group in Xcode named `Frameworks`
- Drag Facebook SDK projects in `Frameworks` group

![image](https://cloud.githubusercontent.com/assets/1970057/9913252/30d2083c-5cac-11e5-9273-1fc7b6772fe2.png)

**Comment by tnguyen42** [comment]
Hi,

You probably skipped the part where you're supposed to modify AppDelegate.m and Info.plist.
These steps are described on the Facebook app part.

**Comment by nlhkh** [comment]
Also check your `Framework Search Paths` under `Build Settings`/`Search Paths`. In my case it was empty, so I had to copy the path of the SDK over.

**Comment by Sherlock92** [comment]
So i had a few more attempts but still no success. I followed all of the steps, and checked the search paths. Here is the error I'm now seeing. I'm clearly missing something drastic, any help is appreciated.

![image](https://cloud.githubusercontent.com/assets/1970057/10223965/0ab4cdfe-685c-11e5-8523-c26963ced090.png)

cc/ @tnguyen42 @nlhkh

**Comment by nlhkh** [comment]
Perhaps I can make a video in the weekend so that you can follow.

**Comment by Sherlock92** [comment]
@nlhkh that would be really great!

**Comment by naoisegolden** [comment]
I had the same issue, ended up using CocoaPods.

**Comment by udfalkso** [comment]
I had this issue, will share what worked for me after a lot of hair pulling.  The problem was that the included xcode project files all have the framework locations set to look in the default of ~/Documents/FacebookSDK.  For various reasons, I don't want the file there but I want them to be inside my project.  

What I ended up doing was adding all the files for each library inside iOS/ directory instead of just the xcodeproject file.  Then everything started to work without this error.  I made a Group for each to keep it sane.  

![screen shot 2015-10-02 at 12 27 32 pm](https://cloud.githubusercontent.com/assets/2029383/10251740/f9a17774-6900-11e5-9798-1ccb109efe18.png)

**Comment by alfonsodev** [comment]
I had the same problem when adding
#import <FBSDKCoreKit/FBSDKCoreKit.h>

What should be the path in Framwork Search Paths, should it point to ~/Documents/FacebookSDK  ? 
Or to the project Framworks path ?

**Comment by alfonsodev** [comment]
@udfalkso  : What about libRCTFBSDKLogin.a ? don't you link it ? 
I have the exactly same issue shown at @Sherlock92 's screenshot.
My Search paths settings  for libraries are empty, what's the correct value there ? 
Thank you.

**Comment by Sherlock92** [comment]
@alfonsodev - FYI my search path includes the default Facebook SDK location of ~/Documents/FacebookSDK

**Comment by alfonsodev** [comment]
@nlhkh if you could make that video would be awesome,  
@Sherlock92 it's still failing for you ? did you try @udfalkso approach ?

**Comment by Sherlock92** [comment]
@alfonsodev I tried all the different approaches but it's still failing for me unfortunately. I will park this I think, until @nlhkh saves the day with his video :)

**Comment by alfonsodev** [comment]
@Sherlock92 , I got the Sample app working on iOS9 XCode 7 react-native 0.12.0-rc , 
I created [this fork/branch](https://github.com/alfonsodev/react-native-fbsdk/tree/iOS9-React0.12-rc  
) and made a [PR](https://github.com/facebook/react-native-fbsdk/pull/44)  
if you download from that branch, npm install and build should work. 
I hope it helps.

**Comment by nlhkh** [comment]
Here is the video [https://youtu.be/yQi6F4Dh6gY](https://youtu.be/yQi6F4Dh6gY). I was too tired to do narration, so bear with my annotations :).

**Comment by Sherlock92** [comment]
Hey @nlhkh - thanks for the video. 

I tried following along with your steps with a new project, but for me the build fails after adding the facebook sdk with: `ld: 260 duplicate symbols for architecture x86_64` :(

**Comment by nlhkh** [comment]
I had that error and it just disappeared on a new project. I have very limited (none) experience in Xcode to comment any further. Perhaps you can send me the zip of your project and let me have a look?

**Comment by alfonsodev** [comment]
@Sherlock92 you could also download my branch and test the Sample project, that has a basic Facebook Login and Share example.
```
git clone -b iOS9-React0.12-rc https://github.com/alfonsodev/react-native-fbsdk
cd react-native-fbsdk
npm install 
open Sample/NHSample.xcodeproj
```
I can confirm that it works for me on: 
- OSX 10.10.5
- XCode 7.0 (7A220)
- React native v0.12.0-rc
- iOS 9

**Comment by dzhuowen** [comment]
Update README file in release0.0.6

**Comment by mrspeaker** [comment]
I think the README needs to have more information. At the moment it says "1. Ensure that the Facebook SDK frameworks are installed and in the right place. 2. Add the folder where the Facebook SDK was to the project's framework search path in Xcode. See Apple's documentation on including frameworks."

Both of these aren't really helpful - they say what is wrong but not how to text or fix it. For me the second one fixed it, but I only knew how to do that by following a comment above (targets -> "your project" -> build settings -> Search paths -> Header Search Path. Add ~/Documents/FacebookSDK").

It would be good if that was added (or at least point to this issue) because it's confusing.

**Comment by joshbedo** [comment]
Definitely confusing I can't get this working with the Podfile. I've only ever gotten it to work by manually doing it and tinkering around with things for 2 hours.
