### ISSUE TITLE
'React/RCTComponentEvent.h' file not found RCTFBSDKLoginButtonManager.m

### ISSUE THREAD

**Issue by khemmapon** [facebook/react-native-fbsdk#580]
## 🐛 Bug Report
'React/RCTComponentEvent.h' file not found RCTFBSDKLoginButtonManager.m when I build debug in iOS

![Screen Shot 2562-07-01 at 18 27 46](https://user-images.githubusercontent.com/19380990/60433178-5a5d3f80-9c2e-11e9-9d56-004f830c5159.png)

## Environment
"react-native": "0.59.9",
"react-native-fbsdk": "1.0.0-rc.4"

**Comment by jdnichollsc** [comment]
Same issue debugging from terminal (using 1.0.0-rc.4 and RN 0.59.9):
```
node_modules/react-native-fbsdk/ios/RCTFBSDK/login/RCTFBSDKLoginButtonManager.m:22:9: fatal error: 'React/RCTComponentEvent.h' file not found
#import <React/RCTComponentEvent.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by Hatzl** [comment]
same issue

**Comment by iMJumpmxn** [comment]
still in 1.0.0-rc.5

**Comment by dsblv** [comment]
`1.0.0` only supports RN 0.60 and up: https://github.com/facebook/react-native-fbsdk/releases/tag/v1.0.0-rc.0

**Comment by vshy108** [comment]
Yes, I build with RN0.60.3 also have this problem, the React target build seem like does not include the header file

**Comment by vshy108** [comment]
I have a temporarily solution for this problem.

I add the project's node_modules/react-native/React/Base full path to Header Search Paths for the RCTFBSDK.xcodeproj in the Libraries...

and change the 

`#import <React/RCTComponentEvent.h>`
to 
`#import <RCTComponentEvent.h>`

in the 

node_modules/react-native-fbsdk/ios/RCTFBSDK/login/RCTFBSDKLoginButtonManager.m

and then I can successfully build it.

**Comment by IShotTheSheriff** [comment]
Following @vshy108 solution I ended up getting `1366 duplicate symbols for architecture x86_64` error instead of original one :/.

**Comment by Xetoxyc** [comment]
I found a fix for this issue.

Open React.xcodeproj > Build Phases > Copy Headers > Add RCTComponentEvent.h

This header is also missing if i run a clean installation of react-native package 0.60.0

**Comment by Xetoxyc** [comment]
> I found a fix for this issue.
> 
> Open React.xcodeproj > Build Phases > Copy Headers > Add RCTComponentEvent.h
> 
> This header is also missing if i run a clean installation of react-native package 0.60.0

I recreated my full project with npx react-native init und started using npx react-native run-is and cocoa pods... With using pods and npx the error is gone. It seems like its pretty "complicated" to upgrade 0.59 -> 0.60.

I suggest to invest some time and recreate your project with npx and pods... this also activates autolinking

**Comment by msqar** [comment]
@Xetoxyc you saved me!!! thanks

**Comment by leandrolimasi** [comment]
> I found a fix for this issue.
> 
> Open React.xcodeproj > Build Phases > Copy Headers > Add RCTComponentEvent.h
> 
> This header is also missing if i run a clean installation of react-native package 0.60.0

this approach worked for me, but my pipeline never gets the fix to build the app because the fix was introduced in "node_modules/react-native/React" folder which is cleared before every build. Is there another solution for that?

**Comment by Xetoxyc** [comment]
> > I found a fix for this issue.
> > Open React.xcodeproj > Build Phases > Copy Headers > Add RCTComponentEvent.h
> > This header is also missing if i run a clean installation of react-native package 0.60.0
> 
> this approach worked for me, but my pipeline never gets the fix to build the app because the fix was introduced in "node_modules/react-native/React" folder which is cleared before every build. Is there another solution for that?

Try https://github.com/facebook/react-native-fbsdk/issues/580#issuecomment-512785354 this seems to be the only working solution right now.

**Comment by msqar** [comment]
Guys, after properly installing 0.60.5 and latest FBSDK with cocoapods, this was no longer a problem. I had no issues related to React nor ComponentEvent.h missing. I just run pod install and everything works smooth.

**Comment by karltaylor** [comment]
> `1.0.0` only supports RN 0.60 and up: https://github.com/facebook/react-native-fbsdk/releases/tag/v1.0.0-rc.0

This would be great on the `README.md` 🙂

**Comment by BaderSerhan** [comment]
> I found a fix for this issue.
> 
> Open React.xcodeproj > Build Phases > Copy Headers > Add RCTComponentEvent.h
> 
> This header is also missing if i run a clean installation of react-native package 0.60.0


This works for me but I have to manually do it after every `yarn add` or `npm install`.
The header should be added to `React` on its new release.
