### PR TITLE
Need for 0.5.0 version patch - use 4.22.1 version of facebook-android-sdk

### PR DESCRIPTION
**Pull request by marysieek**
Hi,

Facebook Android SDK was updated yesterday (https://github.com/facebook/facebook-android-sdk/commit/d47ac9335772a05e9f6693674eb3cca4a85342bd) and due to this fact, we cannot longer use `facebook-android-sdk 4.+` version in android/build.gradle for `0.5.0` tag, since it results in regression.

The issue is as follows:
```
:react-native-fbsdk:processReleaseResources/[mydir]/src/
node_modules/react-native-fbsdk/android/build/intermediates/
res/merged/release/values-v24/values-v24.xml:3: 

AAPT: Error retrieving parent for item: 

No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
```

Please release 0.5.1 version with fix applied. 😊

### CODE REVIEW

**Comment by marysieek** [comment]
It is a good practice to use 4.22.1 version explicitly, to avoid regression in the future

**Comment by fcmatteo** [comment]
Same for 0.4.0

**Comment by dev6rodn** [comment]
I've been battling this issue since Wednesday. Getting this PR in soon would be much appreciated.

**Comment by richardfat7** [comment]
Also update your $root\android\app\build.gradle with explicit version if you have added fbsdk as dependency

**Comment by dev6rodn** [comment]
For the sake of completeness, here are the changes I made to get past this issue until the fix is in

android\build.gradle
```
dependencies {
    compile project(':react-native-fbsdk')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"
    //compile 'com.facebook.android:facebook-android-sdk:[4,5)' 
    compile 'com.facebook.android:facebook-android-sdk:[4.22.1)' 
}
```
 
node_modules\react-native-fbsdk\android\build.gradle
```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.0'
    compile 'com.facebook.react:react-native:+' // support react-native-v0.22-rc+
    // compile('com.facebook.android:facebook-android-sdk:4.+')
    compile('com.facebook.android:facebook-android-sdk:4.22.1')
}
```

**Comment by jhilden** [comment]
this might make it a little easier to make the change repeatedly (after a new install or on other team members' machines):

`sed -i 's/facebook-android-sdk:4.+/facebook-android-sdk:4.22.1/g' ./node_modules/react-native-fbsdk/android/build.gradle`

**Comment by rodnolan** [comment]
Yes, that's correct, @jhilden. Thanks for catching that one.

**Comment by dev6rodn** [comment]
Yes, that's correct, @jhilden. Thanks for catching that one. I just updated my previous comment.

**Comment by ricardofbarros** [comment]
Can we get this merged asap?

**Comment by vik228** [comment]
Please merge this PR as soon as possible..As out app is not working on production.

**Comment by ricardofbarros** [comment]
ping @dzhuowen

**Comment by tugorez** [comment]
@vik228 in the meantime you could fork the latest working branch and apply this change to your forked version, then replace the dependency and voila!

Actually I did that  [here](https://github.com/tugorez/react-native-fbsdk),  and  in my project

```sh
yarn add react-native-fbsdk@https://github.com/tugorez/react-native-fbsdk
```
and everything is working fine. Hope it helps

**Comment by kelset** [comment]
I can confirm that on version `0.6.0` still problem still exists, thanks to @dev6rodn for pointing out a workaround - I just add to modify the `node_modules\react-native-fbsdk\android\build.gradle` as shown in his comment.

**Comment by dev6rodn** [comment]
Instead of modifying the node_modules\react-native-fbsdk\android\build.gradle file, you can get the same outcome by modifying your root build.gradle. Again, for the sake on completeness, here's everything in one place. This is far better because you're free to remove and reinstall your node_modules\ if necessary.

android\app\build.gradle
```
dependencies {
    compile project(':react-native-fbsdk')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"
    //compile 'com.facebook.android:facebook-android-sdk:[4,5)' 
    compile 'com.facebook.android:facebook-android-sdk:[4.22.1)' 
}
```

android\build.gradle
```
buildscript { ... }

project(':react-native-fbsdk') {
  configurations.all {
    resolutionStrategy {
      force 'com.facebook.android:facebook-android-sdk:4.22.1'
    }
  }
}
...
allprojects {
    repositories {
        ...
        configurations.all {
            resolutionStrategy {
              force 'com.facebook.android:facebook-android-sdk:4.22.1'
            }
        }
    }
}
```

credit to the fine folks who commented [here](https://stackoverflow.com/questions/44190829/facebook-sdk-android-error-building).

**Comment by mayuce** [comment]
I found it, I was trying to compile my app which is using facebook sdk. I was made that like augst 2016. When I try to open it today i got same error. I had that line in my gradle " compile 'com.facebook.android:facebook-android-sdk:4.+' " and I went https://developers.facebook.com/docs/android/change-log-4x this page and i found the sdk version while i was running this app succesfully and it was 4.14.1 then I changed that line to " compile 'com.facebook.android:facebook-android-sdk:4.14.1' " and it worked.

**Comment by adriancuco** [comment]
Hi,
Still getting the issue 0.6
Please advise about my settings:
apply plugin: 'com.android.library'

android {
    compileSdkVersion 25
    buildToolsVersion "23.0.1"

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 23
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile 'com.android.support:appcompat-v7:25.0.0'
    compile 'com.facebook.react:react-native:+' // support react-native-v0.22-rc+
    compile('com.facebook.android:facebook-android-sdk:4.+')
}

Thanks a lot

**Comment by GeoffreyPlitt** [comment]
Is this getting merged?

**Comment by farazs** [comment]
@dzhuowen seems to be the one who merges pull requests. could we get this merged?

react-native-fbsdk is currently unusable for anyone not able to upgrade their react-native version I believe

**Comment by dzhuowen** [comment]
Instead of setting the fbsdk to specific version,  you can also update the android support library to  25.0.0 in android\app\build.gradle. This shouldn't change any current behavior of the app.
`
android {
    compileSdkVersion 25
    buildToolsVersion "23.0.1"
   ...
}

dependencies {
    compile project(':react-native-fbsdk')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:25.0.0"
    compile "com.facebook.react:react-native:+"  // From node_modules
}
`

**Comment by koenpunt** [comment]
@dzhuowen I tried that, but caused problems with other native modules for some reason..

**Comment by kelset** [comment]
Same here, changing the `compileSdkVersion` to 25 create a lot of issues and in older versions of Android (<5) permissions won't get setup properly.

**Comment by stoffern** [comment]
@dev6rodn solution works fine as a workaround..

**Comment by marysieek** [comment]
Hi @dzhuowen,

I would only like to mention, that compileSdkVersion supported by Facebook is 23 (https://facebook.github.io/react-native/docs/android-building-from-source.html as a reference). Why do you ask other developers to update their build.gradle file using versions that are not officially supported?

Furthermore, builds of dependencies should be predictable, consistent and deterministic. That said, using dynamic versions with “+” sign is a bad practice, because in this case changing the version results in different output.

**Comment by marysieek** [comment]
@dzhuowen For example, this is what happens when using higher and unsupported build tools:
https://github.com/facebook/react-native-fbsdk/pull/338

**Comment by adriancuco** [comment]
@dzhuowen I tried the wordaround and got the following erro:

android/app/src/main/java/com/mytest5/MainApplication.java:29: error: constructor FBSDKPackage in class FBSDKPackage cannot be applied to given types;
            new FBSDKPackage()
            ^
  required: CallbackManager
  found: no arguments
  reason: actual and formal argument lists differ in length
1 error
:app:compileDebugJavaWithJavac FAILED

**Comment by stoffern** [comment]
@adriancuco this is not related to this problem. You have not defined a callback function.
Please follow the docs on CallbackManager and how to add the functions that you need.

**Comment by adriancuco** [comment]
@stoffern it is related. When applied the @dzhuowen's workaround, this issue comes out.

**Comment by rodnolan** [comment]
@adriancuco have you followed all [these instructions](https://github.com/facebook/react-native-fbsdk#31-android-project)? Your error indicates that you're missing an argument... that argument is described in that section.

**Comment by adriancuco** [comment]
@rodnolan. Ahhh, understood.
Sorry about that.

Let me check it out.

Thx

**Comment by stoffern** [comment]
@adriancuco not related 😉

**Comment by eduplus** [comment]
If you only up your own compileSdk and build tools, other libraries will complain, but this will help fix those, without changes inside node_modules:

ext {
    compileSdkVersion = 25
    buildToolsVersion = '25.0.3'
}

subprojects { subproject ->
    afterEvaluate{
        if((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
            }
        }
    }
}

**Comment by dev6rodn** [comment]
I have my app running smoothly now with the latest versions of all my dependencies (react, react-native, react-native-fbsdk, etc) and I'm using version 23 of the sdk and build tools. I went through the upgrade process described here: http://facebook.github.io/react-native/docs/upgrading.html. It required some work but I'm glad I did it. I still have to lock down the Android Facebook SDK at version 4.22.1 but that's a minor adjustment, given the version mess I was creating by downgrading my dependencies.

Here's my latest configuration. Your mileage may vary but this is what's working for me right now. 

package.json
```
  "dependencies": {
    "native-base": "^2.1.4",
    "react": "16.0.0-alpha.12", 
    "react-native": "~0.45.0", 
    "react-native-deprecated-custom-components": "^0.1.0",
    "react-native-fbsdk": "^0.6.0", 
    "react-native-facebook-account-kit": "^0.6.2",
    "react-native-image-crop-picker": "^0.13.1",
    "react-native-modal": "^2.0.2",
    "react-native-photo-grid": "0.0.2",
    "react-native-storage": "^0.2.2",
    "react-native-view-shot": "^1.9.1",
    "react-navigation": "^1.0.0-beta.5"
  },
```

android\build.gradle
```
project(':react-native-fbsdk') {
    configurations.all {
        resolutionStrategy {
            force 'com.facebook.android:facebook-android-sdk:4.22.1'
        }
    }
}
...
allprojects {
    repositories {
        ...
        configurations.all {
            resolutionStrategy {
                force 'com.facebook.android:facebook-android-sdk:4.22.1'
            }
        }
    }
}
```

android\app\build.gradle
```
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"
    ...
}
...
dependencies {
    compile project(':react-native-fbsdk')
    compile project(':react-native-view-shot')
    compile project(':react-native-image-crop-picker')
    compile project(':react-native-facebook-account-kit')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"
    compile('com.facebook.android:facebook-android-sdk:4.22.1')
}
```

**Comment by igorarkhipenko** [comment]
@dev6rodn Is it still working fine for you? Tried exactly the same configuration with my build and got an error. 
`No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.`

I wonder this branch is not merged yet.

**Comment by rodnolan** [comment]
@igorarkhipenko my app is still compiling without error. You may have to clean up a few things in order to get over the hump. Give this a try, if you haven't already. 
```
del node_modules\*
yarn install (or npm install)
cd android
gradlew clean
cd ..
react-native run-android
```

**Comment by igorarkhipenko** [comment]
@rodnolan unfortunately, didn't work for me neither. Anyway, thank you for your fast response, sir. Seems like, I've got a worm somewhere in my code.

**Comment by rodnolan** [comment]
It was a lot of work but it was helpful to gradually rebuild my app from scratch. I started with a blank app and copied my old code into the new project piece by piece, chunk by chunk. I was very methodical in verifying every major step I took but I eventually found the finish line. Good luck. ;-)

**Comment by cdimitroulas** [comment]
Is this going to be merged or not? I do not want to have to manually fix the Facebook SDK to version 4.22.1.

**Comment by mortezaalizadeh** [comment]
Is there any plan to merge this back to master branch? My app is completely broken :(

**Comment by stoffern** [comment]
cc @dzhuowen

**Comment by dzhuowen** [comment]
Sorry for the inconvenience. We'll do a 0.6.1 release to fix sdk version.

**Comment by cdimitroulas** [comment]
Did you mean 0.5.1?

**Comment by stoffern** [comment]
current version is 0.6.0 and he will push a bugfix out, that makes versioning automatic to 0.6.1..

**Comment by cdimitroulas** [comment]
But that means I need to upgrade my version of react-native-fbsdk to 0.6.0 just for this...

**Comment by farazs** [comment]
Also I believe 0.6.0 requires RN 0.44 or later so it might require a react native upgrade as well.

**Comment by stoffern** [comment]
@farazs Thanks for info,
@dzhuowen in order to make the bugfix backward compatible please release a 0.5.1 fix to.
see above comments

**Comment by dzhuowen** [comment]
:thumbsup:

**Comment by kelset** [comment]
Why is 0.6.0 using build tools 25? As said by @marysieek up [here](https://github.com/facebook/react-native-fbsdk/pull/339#issuecomment-306427835) it is not a good idea to up them.

I guess I'll have to wait for 0.5.1 and stick to that.

**Comment by Lensi** [comment]
Still having the issue on 0.6.1.
dev6rodn's workaround still does it though.

**Comment by pawlowskim** [comment]
Still not working on 0.5.0. Moreover, @marysieek deleted her repo

**Comment by jhilden** [comment]
We upgraded to version `0.5.1` (I think nobody mentioned here yet that this has finally been built and released to npm 3 days ago) and it fixed the issue for us, while still allowing us not to upgrade React Native just yet (we are still on `0.42`).

**Comment by pawlowskim** [comment]
React-native 0.44.0 and react-native-fbsdk -0.5.1 also works.

**Comment by cdimitroulas** [comment]
I am still having this issue but I can see that version `0.5.1` is installed and that the gradle file inside the fbsdk node_module indeed is pointing to the `4.22.1` version of the sdk.

I can get my project to build using the workaround from [this](https://stackoverflow.com/questions/44190829/facebook-sdk-android-error-building/44205756#44205756) StackOverflow answer which proves that this is related to the react-native-fbsdk.

Is it possible that this is a caching issue? I have tried a variety of different commands to try to get around this but to no avail.
I tried various combinations of: `gradlew clean`, `rm -rf node_modules`, `npm clear cache`, `npm install`, `npm start -- --reset-cache`.

Would appreciate some help :sweat_smile:

**Comment by jslok** [comment]
After much debuggin, I updated all these:
gradle to 3.01
gradle wrapper to 4.1
compilesdkversion to 26
buildtoolsversion to 26.02
com.android.support:appcompat-v7 to 26

Now I am able to successfully compile with the latest version of FB SDK.

**Comment by dwicao** [comment]
This was worked flawlessly on me

android\build.gradle
```
...
allprojects {
    repositories {
        ...
        configurations.all {
            resolutionStrategy {
                force 'com.facebook.android:facebook-android-sdk:4.28.0'
            }
        }
    }
}
```
