### ISSUE TITLE
Version clashes?

### ISSUE THREAD

**Issue by djMax** [facebook/react-native-fbsdk#523]
## 🐛 Bug Report
Fresh install of the package and working on Android. iOS build fails with:

```
Use of undeclared identifier 'FBSDKLoginBehaviorNative'; did you mean 'FBSDKLoginBehaviorBrowser'?
```
RCTFBSDKLoginButtonManager.m line 49

## To Reproduce
Follow iOS install instructions

## Expected Behavior
Successful build

## Environment
```
info
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
      Memory: 847.50 MB / 32.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 26, 27, 28
        Build Tools: 28.0.3
        System Images: android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.5 => 0.59.5
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

**Comment by djMax** [comment]
After messing with some pod updates and such, I see this error now:
```
/myapp/node_modules/react-native-fbsdk/ios/RCTFBSDK/core/RCTConvert+FBSDKAccessToken.m:28:13: No visible @interface for 'FBSDKAccessToken' declares the selector 'initWithTokenString:permissions:declinedPermissions:appID:userID:expirationDate:refreshDate:'
```

**Comment by djMax** [comment]
Had to downgrade to 4.42.0

```
  pod 'FBSDKCoreKit', '~>4.42.0'
  pod 'FBSDKLoginKit', '~>4.42.0'
  pod 'FBSDKShareKit', '~>4.42.0'
```

**Comment by akash-rajput** [comment]
This is really bad experience. Please if you can't keep version in sync at least mention them in readme. This is completely misleading.

**Comment by dimgrav** [comment]
Thanks djMax

**Comment by stvmachine** [comment]
The whole library is a mess 😢

**Comment by javi10823** [comment]
I have this issue with React Native, please help

**Comment by javi10823** [comment]
> Had to downgrade to 4.42.0
> 
> ```
>   pod 'FBSDKCoreKit', '~>4.42.0'
>   pod 'FBSDKLoginKit', '~>4.42.0'
>   pod 'FBSDKShareKit', '~>4.42.0'
> ```

@djMax  hey, How can I do this? The library said that we don't have to use pods (skip the step 2 in the installation guide)

**Comment by tuanna1601b** [comment]
@javi10823 just add those lines in your Podfile

**Comment by javi10823** [comment]
> @javi10823 just add those lines in your Podfile

ok @tuanna1601b  it works....

**Comment by IacoCesar** [comment]
> > @javi10823 just add those lines in your Podfile
> 
> ok @tuanna1601b it works....

@javi10823 what is the version of your fbsdk?

**Comment by Samueloyeks** [comment]
but i'm not using pod

**Comment by Sin-** [comment]
Just encountered this issue after upgrading the lib in my project to 0.10.1
The cocoa pods fix did not work as I get an error:
```
CocoaPods could not find compatible versions for pod "FBSDKShareKit":
  In Podfile:
    FBSDKShareKit (~> 4.42.0)
```
This is pretty annoying as I cannot compile the app for a new update anymore.
Any idea?

**Comment by Benjaki2** [comment]
```
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
```
in the podfile
using version   `react-native-fbsdk@1.0.0-rc.5`
solved this for me
Hope this helps.

**Comment by ollydixon** [comment]
The following setup if working for me in.

package.json
`"react-native-fbsdk": "v1.0.0-rc.4",`

Podfile
```
pod 'FBSDKCoreKit', '~> 5.0'
pod 'FBSDKLoginKit', '~> 5.0'
pod 'FBSDKShareKit', '~> 5.0'
pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
```

**Comment by grantd77** [comment]
nothing suggested works for me, I have as close to the above as possible, expect I'm using react-native-fbskcore. I forced the pods to use 5.0.

RCT_ENUM_CONVERTER(FBSDKLoginBehavior, (@{
  @"native": @(FBSDKLoginBehaviorNative),
  @"browser": @(FBSDKLoginBehaviorBrowser),
  @"system-account": @(FBSDKLoginBehaviorSystemAccount),
  @"web": @(FBSDKLoginBehaviorWeb),
}), FBSDKLoginBehaviorNative, unsignedLongValue)

In RCTConvert+FBSKLogin.m, 4 of the above lines have errors of 'Use of undeclared identifier'

What gives? How can this be resolved?

**Comment by rahulbhankar786** [comment]
I found a solution just delete podfile.lock and pod install
