### ISSUE TITLE
Undefined symbols for architecture i386:   "_OBJC_CLASS_$_FBSDKApplicationDelegate"

### ISSUE THREAD

**Issue by jamesone** [facebook/react-native-fbsdk#179]
After upgrading from 0.1 to 0.2 I am getting a lot of errors regarding the auto linking. I've removed the Pods xcworkspace removed references to any of the pods files as I only used pods for RNFBSDK. Any ideas on how I can fix this?? 

Below is the stack trace. 
```
ld: warning: Auto-Linking supplied '/Users/james/Documents/FacebookSDK/Bolts.framework/Bolts', framework linker option at /Users/james/Documents/FacebookSDK/Bolts.framework/Bolts is not a dylib
ld: warning: Auto-Linking supplied '/Users/james/Documents/FacebookSDK/FBSDKCoreKit.framework/FBSDKCoreKit', framework linker option at /Users/james/Documents/FacebookSDK/FBSDKCoreKit.framework/FBSDKCoreKit is not a dylib
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_FBSDKApplicationDelegate", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

Another stack trace:
```
ld: warning: Auto-Linking supplied '/Users/james/Documents/FacebookSDK/Bolts.framework/Bolts', framework linker option at /Users/james/Documents/FacebookSDK/Bolts.framework/Bolts is not a dylib
```

And another:

```
ld: warning: Auto-Linking supplied '/Users/james/Documents/FacebookSDK/FBSDKCoreKit.framework/FBSDKCoreKit', framework linker option at /Users/james/Documents/FacebookSDK/FBSDKCoreKit.framework/FBSDKCoreKit is not a dylib
```

I removed the -Obj-c linker flag as it was producing 34 errors, once removed it only produced this one.

**Comment by jamesone** [comment]
I believe this was because I didn't have the FBSDKcorekit inside the `Frameworks` folder.

**Comment by chrisp-fb** [comment]
Undefined symbols means the framework wasn't linked. Make sure you follow [step 4 of the Getting Started on iOS guide](https://developers.facebook.com/docs/ios/getting-started#addSDK).
